# Default YAML values (more information on Jekyll's site)
destination: "./_landing_page"
excerpt_length: 25
post_search: false
feed_show_excerpt: true
feed_show_tags: false
url: "https://yuribocharov.dev"

blog_domain: "https://blog.yuribocharov.dev"

#landing page links
navbar-links:
  Blog: "https://blog.yuribocharov.dev"
  Resume: "/assets/resume.pdf"
  About:
    - About Yuri: "/about"
    - Projects: "/projects"
    - Movies: "/movies"
defaults:
  - scope:
      path: "" # any file that's not a post will be a "page" layout by default
    values:
      layout: "page"
      no_header: true
      # head-extra: favicon_headers.html
  - scope:
      path: "index.html" # any file that's not a post will be a "page" layout by default
    values:
      layout: "landing"
  - scope:
      path: "assets/css/*.css"
    values:
      layout: null

exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - screenshot.png
  - docs/
  - _site/
  - assets/img/
include:
  - _redirects
