# Default YAML values (more information on Jekyll's site)
destination: "./_landing_page"
excerpt_length: 25
post_search: false
feed_show_excerpt: true
feed_show_tags: false
url: "https://yuribocharov.dev"

pagination:
  enabled: true
  collection: "posts"
  per_page: 3
  permalink: "/page/:num/"
  sort_field: "date"
  sort_reverse: true
  title: ":title"

blog_domain: "https://blog.yuribocharov.dev"

defaults:
  - scope:
      path: "index.html" # any file that's not a post will be a "page" layout by default
    values:
      layout: "landing"
      head-extra: favicon_headers.html
      no_header: true
exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - screenshot.png
  - docs/
  - _site/
include:
  - _redirects
