[tools]
ruby = "3.3.6"
node = "20"

##### TASKS #####

[tasks.landing]
description = "Runs a server with the landing page in dev mode (--prod for prod mode)"
run = """
if [ '{{flag(name='prod')}}' = 'true' ]; then
  export JEKYLL_ENV="production"
  npm run build
  bundle exec jekyll serve --config "_config.yml,_config_landing.yml" --trace --livereload --livereload-port 35731 --port 3001 --incremental
else
  npm run build
  bundle exec jekyll serve --config "_config.yml,_config_landing.yml" --trace --livereload --livereload-port 35731 --port 3001 --unpublished --incremental --future
fi
"""

[tasks.blog]
description = "Runs a server with the blog page in dev mode. (--prod for prod mode)"
run = """
if [ '{{flag(name='prod')}}' = 'true' ]; then
  export JEKYLL_ENV="production"
  npm run build
  bundle exec jekyll serve --trace --livereload --livereload-port 35730 --port 3000 --incremental
else
  npm run build
  bundle exec jekyll serve --trace --livereload --livereload-port 35730 --port 3000 --unpublished --incremental --future
fi
"""

[tasks.setup]
description = "Set up dependencies, gems and packages"
run = 'bin/setup.sh'

[tasks.update]
description = "Update gems and packages"
run = 'bin/update.sh'

[tasks.til]
description = "Create a new TIL blog post with today's date"
run = 'bin/til.sh'

[tasks.build]
description = "Build jekyll site (--landing for landing page.)"
run = """
npm run build
if [ '{{flag(name='landing')}}' = 'true' ]; then
  bundle exec jekyll build --config "_config.yml,_config_landing.yml"
else
  bundle exec jekyll build
fi
"""
