[tools]
ruby = "3.3.6"
node = "20"

##### TASKS #####
#
[tasks.landing]
description = "Runs a server with the landing page in dev mode (--prod for prod mode)"
run = """
if [ '{{flag(name='prod')}}' = 'true' ]; then
  export JEKYLL_ENV="production"
  bundle exec jekyll serve --config "_config.yml,_config_landing.yml" --trace --livereload --livereload-port 35731 --port 3001 --incremental
else
  bundle exec jekyll serve --config "_config.yml,_config_landing.yml" --trace --livereload --livereload-port 35731 --port 3001 --unpublished --incremental --future
fi
"""

[tasks.blog]
description = "Runs a server with the blog page in dev mode. (--prod for prod mode)"
run = """
if [ '{{flag(name='prod')}}' = 'true' ]; then
  export JEKYLL_ENV="production"
  bundle exec jekyll serve --trace --livereload --livereload-port 35730 --port 3000 --incremental
else
  bundle exec jekyll serve --trace --livereload --livereload-port 35730 --port 3000 --unpublished --incremental --future
fi
"""

[tasks.setup]
description = "Set up dependencies, gems and packages"
run = 'bin/setup.sh'

[tasks.update]
description = "Update gems and packages"
run = 'bin/update.sh'
